### ISSUE TITLE
Be able to see any pools you currently delegate to

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/near-staking-ui#10]

**Comment by AngelBlock** [comment]
> and see reward? What can we see just over RPC? Don't want to add in an indexer (yet)
> 
> If rewards not auto compounding, can you see amount available for withdrawal?

 No, rewards are not possible to show with indexer and complex calculation, in this case near-staking.com can help

**Comment by andriy-bs** [comment]
Done, please check
