### ISSUE TITLE
Add a 'News' section

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/near-staking-ui#13]
Add a news item:

[Dec/8 - Launch of Meta Staking Vote - 1 Million NEAR distribution to validator nodes](https://gov.near.org/t/dec-8-launch-of-meta-staking-vote-1-million-near-distribution-to-validator-nodes/31747)

**Comment by paulmattei** [comment]
Simple news feed. Latest item at the top.
news items can go in a json file. title, description and external link for each item is enough for now

**Comment by paulmattei** [comment]
hosted at /news

Also create a new item for this in nav

**Comment by caroline93** [comment]
done
