### ISSUE TITLE
move nav from top of page to a list down the left hand side

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/near-staking-ui#17]

**Comment by paulmattei** [comment]
![image](https://user-images.githubusercontent.com/38218340/206136215-c7d73d76-8f69-40db-8e39-636f91facf34.png)

**Comment by paulmattei** [comment]
Create pool -> /pool
Mount pool -> /coming-2023
Monitoring -> /coming-2023
Stake -> /stake
Rewards -> /coming-2023
News -> /news

**Comment by paulmattei** [comment]
Remove 'rewards' page. Now not immediately needed

**Comment by caroline93** [comment]
done
