### ISSUE TITLE
Base64 encode GrafanaToken

### ISSUE THREAD

**Issue by Mic92** [kuutamolabs/near-staking-ui#179]
https://github.com/kuutamolabs/near-staking-ui/blob/264673a1da70ed13bae7a0e433ed67df7f5d400e/backend/src/services/user/getGrafanaToken.js#L17

Replace: `<p>${user.email}</p><p>${user._id}:${token.token}</p>`

with: 

```
let token = Buffer.from(`${user._id}:${token.token}`).toString('base64');
`<p>${user.email}</p><p>${token}</p>`
```

Also provide the same token for the user to download in a file named: `kuutamo-monitoring.token`

**Comment by paulmattei** [comment]
tested ok
