### ISSUE TITLE
Cancel monitoring setting

### ISSUE THREAD

**Issue by yanganto** [kuutamolabs/near-staking-ui#189]
When a user going to set up monitoring on the following page...
![CouldNotExit](https://github.com/kuutamolabs/near-staking-ui/assets/10803111/1c257712-ab9e-42a7-ba11-ade385fa7ebf)

He can not cancel the monitoring setting, if he does not want to do this now.
We can let user click the blur part and close the pop up box, and go back

**Comment by baliubakh** [comment]
the fix is pushed to develop branch
