### ISSUE TITLE
Do not assume account is a named account

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/near-staking-ui#21]
![image](https://user-images.githubusercontent.com/38218340/205988722-f907d0bd-2ddd-4bac-a88d-e419dcb8e994.png)

But the address via wallet connect is an implicit account.

Also allow the user to 'click to copy' the address currently signed in as, otherwise for implicit account they have to type out all the random chars.

**Comment by paulmattei** [comment]
Also on mainnet. This looks like it assumes “.mainnet” it should be “.near” - and this needs to be an option anyway, to support implicit account.

**Comment by caroline93** [comment]
done
