### ISSUE TITLE
add ability to unstake and withdraw

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/near-staking-ui#26]
This should live in the /stake page

**Comment by AngelBlock** [comment]
and withdraw

**Comment by paulmattei** [comment]
one first see rewards,
unstake all
or
unstake XX

then wait 4 epochs (show time remaining?)

then:

withdraw all
or 
withdraw XX (this we can show)

**Comment by caroline93** [comment]
done

**Comment by paulmattei** [comment]
Can we make it clear with a countdown how long is remaining before near can be withdrawn? Otherwise flow ends up at:

{"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'The unstaked balance is not yet available due to unstaking delay', staking-farm/src/internal.rs:59:9"}} in wallet.

**Comment by caroline93** [comment]
done

**Comment by paulmattei** [comment]
I had 20 that was unstaked a while ago so I was free to withdraw. Then I unstaked another 40. I should now I think be able to withdraw 20 and there should be a timer on the 40, not the whole 60.

![image](https://user-images.githubusercontent.com/38218340/210985345-35a3bf93-f2ad-4e25-ba99-8b739051c338.png)
