### ISSUE TITLE
See rewards and withdraw

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/near-staking-ui#27]
See total rewards available to withdraw, and add withdraw button. In /rewards page.

Stape 2. Add graph showing rewards overtime. This may require indexer. If so, step 2 can wait until Jan.

**Comment by AngelBlock** [comment]
@paulmattei total rewards to withdraw is impossible to show without indexer, I'm afraid.

**Comment by paulmattei** [comment]
Closing for now, lets address #26 first
