### ISSUE TITLE
After pool is launched there should be a 'Finished' button

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/near-staking-ui#85]

**Comment by paulmattei** [comment]
After pool is created - how long should it take for the pool to become visible in the List of validators? Because currently its surprising to the user that it isn't immediately there...

**Comment by andriy-bs** [comment]
@paulmattei  Now the list of validators is updated immediately. Need to redeploy the backend

**Comment by paulmattei** [comment]
Done
