### ISSUE TITLE
Feedback on UI

### ISSUE THREAD

**Issue by caroline93** [kuutamolabs/near-staking-ui#86]
- improve search of current validators
- develop dark mode of the site
- It would be great to have a 'stake max' and 'unstake max' button + these two options should show the amount before you get guide to the NEAR wallet flow.
- it might be better to have the account name next to log in / log out button
- are the pool rewards for my delegations before or after the validator fee has taken it's % fee? it would be nice to see net vs gross
- When clicking 'Validators' on the left, immediately show the list of validators (/pools) page. Remove 'List of Validators' menu option.

**Comment by paulmattei** [comment]
https://test.near.kuutamo.app/stake

"Your Current Validators" -> "Your current delegations"
